workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.cvstunner.vgni"
        ANDROID_APP_PATH: "app/build/outputs/apk/debug/app-debug.apk"
      java: 17
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Download and set up Gradle
        script: |
          wget https://services.gradle.org/distributions/gradle-8.11.1-bin.zip
          unzip gradle-8.11.1-bin.zip
          export PATH=$PATH:`pwd`/gradle-8.11.1/bin
      - name: Clean project
        script: |
          gradle clean
      - name: Build Debug APK
        script: |
          gradle assembleDebug
    artifacts:
      - $ANDROID_APP_PATH
    publishing:
      email:
        recipients:
          - chetanshigwan789@gmail.com
