workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 120
    environment:
      vars:
        PACKAGE_NAME: "com.cvstunner.vgni"
        ANDROID_APP_PATH: "app/build/outputs/apk/debug/app-debug.apk"
      java: 11
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
    scripts:
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - $ANDROID_APP_PATH
    publishing:
      email:
        recipients:
          - chetanshigwan789@gmail.com
